import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";
import * as fs from "fs";

interface blogData {
  title: string;
  content: string;
  author: string;
  metaDesc: string;
  slug: string;
}

interface Props {
  allBlogs: blogData[];
}

const Home: NextPage = (props: Props) => {
  const [blogs, setBlogs] = useState<blogData[]>(props.allBlogs);
  return (
    <>
      <Head>
        <title>GraspTheNet | Conquer the Internet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Script>[alert('Welcome to GraspTheNet!!')]</Script> */}

      <div className={styles.main_home_container}>
        <div className={styles.home_img}>
          <Image src="/thumbnail.jpg" alt="Home Image"></Image>
        </div>

        <main className={styles.main}>
          <div className={styles.blogs}>
            <h2 className={styles.main_heading}>Latest Blogs</h2>
            {blogs.map((blog) => {
              return (
                <Link key={blog.slug} href={`/blogpost/${blog.slug}`}>
                  <a>
                    <div className={styles.blogItem}>
                      <h1 className={styles.blog_title}>{blog.title}</h1>
                      <p>{blog.metaDesc.substr(0, 195)}....</p>
                    </div>
                  </a>
                </Link>
              );
            })}
          </div>
        </main>
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (context: object) => {
  let data: string[] = await fs.promises.readdir("blogdata");
  let myFile;
  let allBlogs: blogData[] = [];
  for (let i = 0; i < data.length; i++) {
    const item = data[i];
    myFile = await fs.promises.readFile(`blogdata/${item}`, "utf-8");
    allBlogs.push(JSON.parse(myFile));
  }
  return {
    props: { allBlogs },
  };
};

export default Home;
